# A short, descriptive name of this building block collection
name: Hydrology building blocks

# Short abstract for this collection (optional)
abstract: |
  Reusable building blocks for Hydrology from the OGC Hydro Domain WG

# Description for this collection (optional)
description: |
 Features from HY_Features model

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.hydro

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available